name: cipherlib
description: Implementations of cryptographic algorithms for encryption and decryption in Dart.
version: 0.2.0
repository: https://github.com/bitanon/cipherlib

environment:
  sdk: '>=2.19.0 <4.0.0'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
  
dependencies:
  hashlib: ^2.3.4

dev_dependencies:
  lints: any
  test: any
  benchmark_harness: any
  cryptography: any
  pointycastle: any

funding:
  - https://paypal.me/bitan0n
