name: cipherlib
description: Pure-Dart cryptography package implementing symmetric ciphers (AES
  with multiple modes, ChaCha20, XChaCha20, Salsa20, XSalsa20, XOR) and their
  AEAD variants with Poly1305.
repository: https://github.com/bitanon/cipherlib
version: 0.4.0

environment:
  sdk: ">=2.19.0 <4.0.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  hashlib: ^2.3.4

dev_dependencies:
  lints: any
  test: any
  cryptography: any
  pointycastle: any

funding:
  - https://paypal.me/bitan0n
